# For build it
#docker build --tag=alpine-java:base --rm=true .

FROM alpine:edge
MAINTAINER baeldung.com
RUN apk add --no-cache openjdk11
#COPY files/UnlimitedJCEPolicyJDK8/* /usr/lib/jvm/java-1.8-openjdk/jre/lib/security/